### ISSUE TITLE
Not checking for actual data in GetOPCNodeList

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/nifi-opcua-bundle#13]
The return value from the stringBuilder from getNamespace on line 178 of GetOPCNodeList is not validated. This will cause null flowfiles to be propagated on the flow. This should be checked and the execution should return with no flow file if the data was not received. A debug message should be logged to the component logger indicating that no response was received from the server, to ensure that we can debug the issue.

**Comment by ed3766** [comment]
Added condition statement to handle empty and null return values.  Closed with pull request #30
