### ISSUE TITLE
JSON timestamp string should be of a different format

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/nifi-opcua-bundle#22]
The JSON timestamp should be yyyy-MM-dd hh:mm:ss

**Comment by ed3766** [comment]
Current format is "10/10/17 07:21:34.8756719 GMT".    Reformat timestamp to yyyy-MM-dd hh:mm:ss to make HBase happy.

**Comment by ed3766** [comment]
Support phoenix timestamp format yyyy-MM-dd HH:mm:ss in both CSV and JSON timestamps

Verify the GetOPCData processor returns the timestamp format yyyy-MM-dd HH:mm:ss  for all DataFormat options (CSV, JSON) and Return Timestamp options (Server, Source) when Use Long Timestamp = false.

{
  "values" : [ {
    "q" : 0,
    "id" : "SimulationExamples.Functions.Ramp1",
    "vs" : "35",
    "ts" : "2017-10-13 17:11:53"
  }, {
    "q" : 0,
    "id" : "SimulationExamples.Functions.Ramp2",
    "vs" : "150.75",
    "ts" : "2017-10-13 17:11:53"
  }...

ns=2;s=SimulationExamples.Functions.Ramp1,2017-10-13 17:11:53,35,0
ns=2;s=SimulationExamples.Functions.Ramp2,2017-10-13 17:11:53,150.75,0
...
