### ISSUE TITLE
Issues Compiling 

### ISSUE THREAD

**Issue by literally38** [hashmapinc/nifi-opcua-bundle#55]
when I run Maven I get the following error
/nifi-opcua-bundle/nifi-opcua-bundle/nifi-opcua-service/src/test/java/com/hashmapinc/tempus/processors/nifi_opcua_services/TestStandardOPCUAService.java:[46,21] error: constructor TestServer in class TestServer cannot be applied to given types;

**Comment by cherrera2001** [comment]
Thanks @literally38 taking a look now... should have some feedback soon

**Comment by cherrera2001** [comment]
What version of the UA-Java library are you using. From a clean pull I can run mvn clean install using the latest: 1.3.344-SNAPSHOT, however, the pom does need to be modified to allow that version. This will be tackled in #56

**Comment by cherrera2001** [comment]
We still have this issue and its tracked in #58
