### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by literally38** [hashmapinc/nifi-opcua-bundle#58]
Hi I am still getting error messages when compiling 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:testCompile (default-testCompile) on project nifi-opcua-service: Compilation failure
[ERROR] bootstrap class path not set in conjunction with -source 8
[ERROR] /Users/Chris/git/nifi-opcua-bundle/nifi-opcua-bundle/nifi-opcua-service/src/test/java/com/hashmapinc/tempus/processors/nifi_opcua_services/TestStandardOPCUAService.java:[46,21] error: constructor TestServer in class TestServer cannot be applied to given types;

any idea what it may be I am using ua stack  1.3.343

**Comment by cherrera2001** [comment]
I am going to setup a clean instance of ubuntu and retry to reproduce this.

**Comment by ed3766** [comment]
Test server only has the following constructor: TestServer(int port)

The issue is in line 46 of TestStandardOPCUAService.java:
    `server = new TestServer(45678, "user", "test");`

**Comment by cherrera2001** [comment]
After extensive screen sharing, and a large dose of it works-on-my-machine-itis @ed3766 and I have managed to fix the situation... It was a maven versioning issue on the embedded test server. It should work now if you follow the readme. Thanks for the report @literally38!
