### ISSUE TITLE
Error swallowed in GetOPCData

### ISSUE THREAD

**Issue by cherrera2001** [hashmapinc/nifi-opcua-bundle#8]
When an error occurs reading from the input file (the taglist flow file) on line 168 of GetOPCData.java, the error is written out to stderr not to the nifi component log. This leads to an issue where a generic "Failed to Read" error is posted to the log, while swallowing the reason.

**Comment by ed3766** [comment]
write error to nifi error log when session returns null flow file.  Closed with pull request #29
